### ISSUE TITLE
Edit tag message

### ISSUE THREAD

**Issue by egpbos** [maartenbreddels/releash#1]
When releasing, it would be nice if I could write my own tag message using my default command line editor. Currently, when the tag message is left empty in the configuration, it adds the `-m ""` option, which gives an empty tag message. The `-m` option should be left out completely to automatlcally have git open an editor. Could you please add this feature? :)

**Comment by maartenbreddels** [comment]
```python
ReleaseTargetGitTagVersion(myself.version_source, msg=None)
```
works from version 0.3
